import React from "react"
import { Text, TextElement, TextProps, Text, Text } from "./Text"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Text,
  "https://www.figma.com/design/O8dYqaa451RmfZmrhKwL94?node-id=2087%3A8487",
  {
    props: {
      text: figma.string("Text"),
    },
    example: (props) => <Text />,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TextElement,
  "https://www.figma.com/design/O8dYqaa451RmfZmrhKwL94?node-id=2104%3A22325",
  {
    props: {
      text: figma.string("Text"),
    },
    example: (props) => <TextElement />,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TextProps,
  "https://www.figma.com/design/O8dYqaa451RmfZmrhKwL94?node-id=2153%3A7834",
  {
    props: {
      hasSubheading: figma.boolean("Has Subheading"),
      heading: figma.string("Heading"),
      subheading: figma.string("Subheading"),
      align: figma.enum("Align", {
        Start: "start",
        Center: "center",
      }),
    },
    example: (props) => <TextProps />,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Text,
  "https://www.figma.com/design/O8dYqaa451RmfZmrhKwL94?node-id=2153%3A7838",
  {
    props: {
      subtitle: figma.string("Subtitle"),
      hasSubtitle: figma.boolean("Has Subtitle"),
      title: figma.string("Title"),
      align: figma.enum("Align", {
        Start: "start",
        Center: "center",
      }),
    },
    example: (props) => <Text />,
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Text,
  "https://www.figma.com/design/O8dYqaa451RmfZmrhKwL94?node-id=2087%3A8488",
  {
    props: {
      text: figma.string("Text"),
    },
    example: (props) => <Text />,
  },
)
